### ISSUE TITLE
FIX: parser for nomad, incorrect parsing for tth values of bank 3 and 4

### ISSUE THREAD

**Issue by dragonyanglong** [CJ-Wright/sidewinder-spec#10]
Hi @CJ-Wright , 
The parser for nomad has a minor error that the theta values for bank 3 and 4 didn't get parsed correctly.

So the resulting gr data of these two banks are incorrect.
I printed out the `bank_info`:
```
{0: {'total flight path': 21.51, 'tth': 15.1, 'total flight path unit': 'm', 'tth unit': 'deg'}, 1: {'total flight path': 21.18, 'tth': 31.0, 'total flight path unit': 'm', 'tth unit': 'deg'}, 2: {'total flight path': 20.64, 'tth': 65.0, 'total flight path unit': 'm', 'tth unit': 'deg'}, 3: {'total flight path': 20.61, 'total flight path unit': 'm', 'tth unit': 'deg'}, 4: {'total flight path': 20.29, 'total flight path unit': 'm', 'tth unit': 'deg'}, 5: {'total flight path': 22.06, 'tth': 8.6, 'total flight path unit': 'm', 'tth unit': 'deg’}}
```

Bank_info[3] and bank_info[4] miss `tth` values.

I think the reason would be that for bank3 and bank4, there are 2 spaces between `tth` and the value. So the `bank parser list` needs to be updated a little bit. I printed the strings below for you to better see the difference for bank3 and bank4 compared with other banks.
from bank 0 to bank 5:

'''
Total flight path   21.510m, tth   15.100deg, DIFC 1428.818756011 
Total flight path   21.180m, tth   31.000deg, DIFC 2861.506614873 
Total flight path   20.640m, tth   65.000deg, DIFC 5606.556361966 
Total flight path   20.610m, tth  120.400deg, DIFC 9041.704899514 
Total flight path   20.290m, tth  150.100deg, DIFC 9910.536905573 
Total flight path   22.060m, tth    8.600deg, DIFC 836.206546490  
'''

**Comment by CJ-Wright** [comment]
Thank you very much for reporting!

**Comment by CJ-Wright** [comment]
I guess I need a slightly smarter regex :sheep:

**Comment by CJ-Wright** [comment]
I think this has been fixed in my fork, would you mind trying it out?

**Comment by dragonyanglong** [comment]
Hi @CJ-Wright , it works perfect now! Thanks a lot. Close the issue?

By the way, could you please help me a quick thing? could you please visualize your pipeline structure and send the image to me? I tried to figure out the version problems of graphiz package but still failed to run `tof_source.visualize('../total_mystream.png')` in pipeline.py.  Also, which version you use for graphiz in your conda environment?

**Comment by CJ-Wright** [comment]
I'm using 
```
graphviz                  2.38.0                        6    conda-forge
graphviz                  0.5.1                     <pip>
pygraphviz                1.3.1                     <pip>
```

**Comment by CJ-Wright** [comment]
Which pipeline do you want? The raw or the one with the event model?

**Comment by dragonyanglong** [comment]
Could you please send me both of them? Thanks you very much, Chris!

I tried to keep the packages with exactly the same version as yours, but still failed. Seems like a non-trivial macOS problem.

**Comment by CJ-Wright** [comment]
Would you mind raising an issue at streamz or streamz_ext?

**Comment by dragonyanglong** [comment]
Sure. issue posted on https://github.com/xpdAcq/streamz_ext/issues/2
